import { join, posix } from 'node:path';

import { writeIfAbsent } from './fs';

const GETDOTENV_CONFIG_TS = `import { defineGetDotenvConfig } from '@karmaniverous/get-dotenv';

import dynamic from './getdotenv.dynamic';

export default defineGetDotenvConfig({
  dynamic,
});
`;

const GETDOTENV_DYNAMIC_TS = `import { defineDynamic } from '@karmaniverous/get-dotenv';

export type GetDotenvDynamicVars = {
  SERVICE_NAME?: string;
  STAGE?: string;
  STAGE_NAME?: string;
  TABLE_VERSION?: string;
  TABLE_VERSION_DEPLOYED?: string;
  TABLE_NAME?: string;
  TABLE_NAME_DEPLOYED?: string;
};

const deriveStage = (vars: GetDotenvDynamicVars, env?: string): string | undefined =>
  vars.STAGE ?? env;

const deriveStageName = (
  vars: GetDotenvDynamicVars,
  env?: string,
): string | undefined => {
  if (vars.STAGE_NAME) return vars.STAGE_NAME;
  const stage = deriveStage(vars, env);
  const svc = vars.SERVICE_NAME;
  if (!svc || !stage) return undefined;
  return \`\${svc}-\${stage}\`;
};

export default defineDynamic<
  GetDotenvDynamicVars,
  {
    STAGE: (vars: GetDotenvDynamicVars, env?: string) => string | undefined;
    STAGE_NAME: (vars: GetDotenvDynamicVars, env?: string) => string | undefined;
    TABLE_NAME: (vars: GetDotenvDynamicVars, env?: string) => string | undefined;
    TABLE_NAME_DEPLOYED: (vars: GetDotenvDynamicVars, env?: string) => string | undefined;
  }
>({
  STAGE: (vars, env) => deriveStage(vars, env),
  STAGE_NAME: (vars, env) => deriveStageName(vars, env),
  TABLE_NAME: (vars, env) => {
    if (vars.TABLE_NAME) return vars.TABLE_NAME;
    const stageName = deriveStageName(vars, env);
    if (!stageName) return undefined;
    const version = vars.TABLE_VERSION ?? '000';
    return \`\${stageName}-\${version}\`;
  },
  TABLE_NAME_DEPLOYED: (vars, env) => {
    if (vars.TABLE_NAME_DEPLOYED) return vars.TABLE_NAME_DEPLOYED;
    const stageName = deriveStageName(vars, env);
    const deployed = vars.TABLE_VERSION_DEPLOYED;
    if (!stageName || !deployed) return undefined;
    return \`\${stageName}-\${deployed}\`;
  },
});
`;

const DOWNSTREAM_CLI_TS = `/**
 * Local CLI entry (tsx).
 *
 * Generated by: \`smoz init --cli\`
 *
 * Mirrors SMOZ's default get-dotenv CLI composition:
 * - SMOZ root commands (init/add/register/openapi/dev)
 * - get-dotenv plugins: aws (with dynamodb), cmd (default), batch
 */
import { dynamodbPlugin } from '@karmaniverous/entity-client-dynamodb/get-dotenv';
import { createCli } from '@karmaniverous/get-dotenv/cli';
import { awsPlugin, batchPlugin, cmdPlugin } from '@karmaniverous/get-dotenv/plugins';

import { useSmozPlugins } from '@karmaniverous/smoz/cli';

const main = async (): Promise<void> => {
  const run = createCli({
    alias: 'smoz',
    branding: 'SMOZ CLI',
    compose: (p) =>
      useSmozPlugins(p)
        .use(awsPlugin().use(dynamodbPlugin()))
        .use(
          cmdPlugin({
            asDefault: true,
            optionAlias: '-c, --cmd <command...>',
          }),
        )
        .use(batchPlugin()),
  });

  await run(process.argv.slice(2));
};

void main();
`;

export const seedRegisterPlaceholders = async (
  root: string,
): Promise<{ created: string[]; skipped: string[] }> => {
  const genDir = join(root, 'app', 'generated');
  const seeds: Array<{ path: string; content: string }> = [
    {
      path: join(genDir, 'register.functions.ts'),
      content:
        '/* AUTO-GENERATED placeholder; will be rewritten by `smoz register` */\nexport {};\n',
    },
    {
      path: join(genDir, 'register.openapi.ts'),
      content:
        '/* AUTO-GENERATED placeholder; will be rewritten by `smoz register` */\nexport {};\n',
    },
    {
      path: join(genDir, 'register.serverless.ts'),
      content:
        '/* AUTO-GENERATED placeholder; will be rewritten by `smoz register` */\nexport {};\n',
    },
  ];
  const created: string[] = [];
  const skipped: string[] = [];
  for (const s of seeds) {
    const { created: c } = await writeIfAbsent(s.path, s.content);
    (c ? created : skipped).push(posix.normalize(s.path));
  }
  return { created, skipped };
};

export const seedGetDotenvScaffold = async (
  root: string,
): Promise<{ created: string[]; skipped: string[] }> => {
  const files: Array<{ path: string; content: string }> = [
    { path: join(root, 'getdotenv.config.ts'), content: GETDOTENV_CONFIG_TS },
    { path: join(root, 'getdotenv.dynamic.ts'), content: GETDOTENV_DYNAMIC_TS },
  ];
  const created: string[] = [];
  const skipped: string[] = [];
  for (const f of files) {
    const { created: c } = await writeIfAbsent(f.path, f.content);
    (c ? created : skipped).push(posix.normalize(f.path));
  }
  return { created, skipped };
};

export const seedCliEntrypoint = async (
  root: string,
): Promise<{ created: string[]; skipped: string[] }> => {
  const outFile = join(root, 'cli.ts');
  const { created: c } = await writeIfAbsent(outFile, DOWNSTREAM_CLI_TS);
  return {
    created: c ? [posix.normalize(outFile)] : [],
    skipped: c ? [] : [posix.normalize(outFile)],
  };
};
