AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table (v000) for the /app fixture
Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${param:STAGE_NAME}-000
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
        - AttributeName: rangeKey
          AttributeType: S
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
        - AttributeName: rangeKey
          KeyType: RANGE
